### ISSUE TITLE
Suggestion - Dependencies

### ISSUE THREAD

**Issue by Caaz** [iseos/VFE-Mechanoid-Tab#1]
So it looks like the intended use-case for this mod is to use it for VFE Mechanoids, but it doesn't look like the mod explicitly requires that mod to be available to work, as the patches already operate via FindMod.

## Idea
If this mod didn't require any additional mods, it could be used by many friendly-mechanoid mods.

## Suggestion
Remove the [VFE dependencies](https://github.com/iseos/VFE-Mechanoid-Tab/blob/main/Mod/About/About.xml#L12-L21) from the About.xml, but leave the `loadAfter` node. This'll ensure that when those mods are active, it'll load it in the correct order, but means players using mods that don't require VFE-Mechanoids, but add mechanoids, can use this mod without adding VFE-Mechanoids or VFE core as well.

**Comment by iseos** [comment]
Good idea, I will do so in the near future.

**Comment by iseos** [comment]
Done
